model_name: /stratch/bounllm/ckpt-500K
task_mode: '' # '[S2S] ', '[NLU] ', '[NLG] '
test_params:
  remove_unused_columns: False
  push_to_hub: False
  report_to: wandb
  do_train: False
  do_predict: True
dataset_loc: ""
