model_name: /stratch/bounllm/ckpt-500K
task_format: conditional_generation
task_mode: '' # '[S2S] ', '[NLU] ', '[NLG] '
adafactor_scheduler: True
training_params:
  num_train_epochs: 10
  evaluation_strategy: epoch
  save_strategy: epoch
  logging_dir: ./logs
  logging_steps: 100
  save_total_limit: 3
  remove_unused_columns: False
  push_to_hub: False
  predict_with_generate: True
  report_to: wandb
