defaults:
  - default

model_name: t5-small
dataset_name: tr_news
task: summarization
task_format: conditional_generation
max_input_length: 768
max_target_length: 128
training_params:
  num_train_epochs: 10
  evaluation_strategy: epoch
  early_stopping_patience: 2
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  save_strategy: epoch
  logging_dir: ./logs
  logging_steps: 100
  save_total_limit: 3
  remove_unused_columns: False
  push_to_hub: False
  output_dir: ./t5_finetuned_test


